### ISSUE TITLE
error: invalid quantity when using quote_order_quantity in market orders

### ISSUE THREAD

**Issue by Th0rgal** [Th0rgal/binance.py#10]
Description of the error:
For some pairs and specific amounts (e.g. FTM_BTC with 0.004 BTC).

Cause(s) of the error:
stepSize if wrong in LOT_SIZE filter for quote_order_quantity  (this should only be used for quantity). I'm going to contact binance in order to know what I should use instead.

**Comment by MrChuckomo** [comment]
One question for clarification - what's the solution to this issue? 
Is it resolved in the latest release [v1.8.1](https://github.com/Th0rgal/binance.py/releases/tag/1.8.1)?

**Comment by Th0rgal** [comment]
yeah it should be fixed with latest version
