### ISSUE TITLE
Dependencies were not installed

### ISSUE THREAD

**Issue by MrChuckomo** [Th0rgal/binance.py#13]
Unfortunately the dependencies were not installed by following the `pip` installation procedure on [pypi](https://pypi.org/project/binance.py/):  
`pip install binance.py`

After the installation `aiohttp` was missing - which you defined in your `requirements.txt`

Looks like the [install_requires](https://packaging.python.org/discussions/install-requires-vs-requirements/) keyword is missing in the `setup.py`

💡 Maybe you can dynamically read out the `requirements.txt` in your `setup.py` and attach a list of required packages. Then you still have just one source for maintaining all your required package.

**Comment by Th0rgal** [comment]
Hello @MrChuckomo,

Thanks for reporting the issue. You can make a PR or I'll work on it asap.

**Comment by Th0rgal** [comment]
Thanks, merged!
