### ISSUE TITLE
KeyboardInterrupt catch?

### ISSUE THREAD

**Issue by DennyZen** [Th0rgal/binance.py#5]
i've tried catch it with :
```
except KeyboardInterrupt as e:
        loop.stop()
        print("Received KeyboardInterrupt, shutting down...")
```
But its working so slowly...
maybe another, more simple way to do this..?

**Comment by Th0rgal** [comment]
Hello there,

What are you exactly trying to do? Doesn't the program already stop by itself when you do ctrl+c? By the way, do you use windows, linux or macos? I use nixos (linux) and the CTRL+C is instantaneous but it seems to me that under windows it takes a lot of time (I don't know why yet but I'm going to read more about it).

**Comment by DennyZen** [comment]
That's what i mean)
i've tested it under windows and really..
> under windows it takes a lot of time
wanted just run it and try..

**Comment by DennyZen** [comment]
thank you for your sharing

**Comment by DennyZen** [comment]
which variables can i use inside my order_update_handler ?
i mean order_quantity, side - what else?
same that listed here? [https://th0rgal.gitbook.io/binance-py/events-list]

**Comment by Th0rgal** [comment]
> which variables can i use inside my order_update_handler ?
> i mean order_quantity, side - what else?
> same that listed here? [https://th0rgal.gitbook.io/binance-py/events-list]

Yup exactly, everything listed here: https://th0rgal.gitbook.io/binance-py/events-list#order-update

It is just a wrapper for this: https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#order-update
