### ISSUE TITLE
package name conflict

### ISSUE THREAD

**Issue by seismars** [Th0rgal/binance.py#9]
I have https://github.com/sammchardy/python-binance installed on my machine. Recently I installed your package as well.
Now my previous code utilizing the old package fail to run, because both use 'import binance'.
I don't know how do deal with the conflict, so I end up uninstall your package (more recent installation) in order to use the previous package, and reinstall the new one while testing the new package.
Any suggestions for an easier co-existence solution?

**Comment by Th0rgal** [comment]
Hmm, could you use pip or conda to create a different environment per project or do you need to use both libraries in the same?

**Comment by seismars** [comment]
If there is no easier workaround I can uninstall/reinstall whenever I want to test your new package. Until I can switch I will have to use the previous package for my existing scripts. Thanks.

**Comment by Th0rgal** [comment]
One solution could be to rename your previous library but I'm not sure of how to do that and you'ld need to edit your existing scripts.

**Comment by seismars** [comment]
I don't know how to rename either packages. Change my scripts is pretty easy.

**Comment by Julien00859** [comment]
Using one dedicated virtual environment per project is the best way to get them isolated from one another.

**Comment by Julien00859** [comment]
@seismars are you still facing troubles installing binance ?

**Comment by seismars** [comment]
Yes. My workaround is to uninstall/reinstall, depending on which binance package I am going to use. I don't know how I can rename the package name when installing, or build dedicated virtual environments per project. I will learn more on this later on.

**Comment by Th0rgal** [comment]
> Yes. My workaround is to uninstall/reinstall, depending on which binance package I am going to use. I don't know how I can rename the package name when installing, or build dedicated virtual environments per project. I will learn more on this later on.

I'ld suggest you to use virtual env (https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/26/python-virtual-env/) or conda.

**Comment by seismars** [comment]
thanks. Will check it out later.
